language: ruby

rvm:
- 2.0.0
- 1.9.3
- 1.9.2
- ruby-head

env:
- "CHEF_VERSION="
- "CHEF_VERSION='~> 11.6.0'"
- "CHEF_VERSION='~> 11.4.4'"
- "CHEF_VERSION='~> 10.26'"
- "CHEF_VERSION='~> 0.10.10'"

matrix:
  allow_failures:
  - rvm: ruby-head
  exclude:
  - rvm: 2.0.0
    env: "CHEF_VERSION='~> 11.4.4'"
  - rvm: 2.0.0
    env: "CHEF_VERSION='~> 10.26'"
  - rvm: 2.0.0
    env: "CHEF_VERSION='~> 0.10.10'"
