language: ruby

rvm:
  - 2.1
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - ruby-head

env:
  - "CHEF_VERSION="
  - "CHEF_VERSION='~> 11.14.2'"
  - "CHEF_VERSION='~> 11.4.4'"
  - "CHEF_VERSION='~> 10.26'"

bundler_args: --without guard

matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 2.1
      env: "CHEF_VERSION='~> 11.4.4'"
    - rvm: 2.1
      env: "CHEF_VERSION='~> 10.26'"
    - rvm: 2.0.0
      env: "CHEF_VERSION='~> 11.4.4'"
    - rvm: 2.0.0
      env: "CHEF_VERSION='~> 10.26'"

addons:
  code_climate:
    repo_token:
      secure: "Apwuy7PdnWsOjQqkVYIfZQIcECns0D+eNecRmG0dQguBbgnQfG9xMMGIwuLshubhs9rPqAac/Bg9ZyIjWBa57V/ehaQg7BTzaN8K76R98lgrQ4Ub3bYoCU91zc554g4sgKMf5K8P5f1NLYGEyDb5+QP4oeafF1UDxwVHL17hHq0="
